<?xml version="1.0" encoding="UTF-8"?>
<project name="sq_c" default="jar" basedir=".">
    <description>Builds, tests, and runs the project .</description>
    <import file="nbproject/build-impl.xml"/>

    <target name="run" depends="init,jar">
        <my-special-exec jadfile="${dist.dir}/${dist.jad}"/>
    </target>

    <target name="jar-all">
        <property name="target.to.call" value="jar"/>
        <antcall target="for-all-configs"/>
    </target>

    <target name="pre-jar">
        <copy todir="${build.classes.dir}">
            <fileset dir="src" includes="*.mg"/>
        </copy>
    </target>

</project>
